name: first-exercise-workflow.yaml
on: [push, pull_request]

jobs:
  shell-cmd-job:
    runs-on: ubuntu-latest
    steps:
      - name: check version
        run: |
          python --version
          pip --version