name: excercise shell
on: [push]
defaults:  # Workflow Level defaults
  run:
    shell: bash
jobs:
  show-working-directory-linux:
    runs-on: ubuntu-latest
    steps:
      - name: 
        run: |
          echo "It's Ubuntu"
          uname -a

  show-working-directory-win:
    runs-on: windows-latest
    defaults:  # Job Level Defaults
      run:
        shell: pwsh
    steps:
      - name: 
        run: |
          echo "windows"
          Get-ComputerInfo
    
      - name: Python Shell 
        shell: python  # Step Level Default Shell
        run: |
          import sys
          print(sys.version)
          
      - name: Python Shell 
        shell: python  # Step Level Default Shell
        run: |
          import sys
          print(sys.version)

      - name: Node Shell 
        shell: node  # Node.js 환경에서 실행하도록 변경
        run: |
          console.log(process.version)
